WIP: Correct etcd client API function specs
zhongwencool/eetcd pull request #38
Opened 2021-12-22 07:21 UTC by belltoy

WIP this PR depends on https://github.com/zhongwencool/rebar3_eetcd_plugin/pull/3 and maybe the next version of `rebar3_eetcd_plugin`

2021-12-22 07:25 UTC, zhongwencool commented
OK, I will review this later. thanks!

2021-12-22 10:37 UTC, zhongwencool requested changes

2021-12-22 10:37 UTC, zhongwencool commented on rebar.config
> +    {rebar3_eetcd_plugin, {git, "https://github.com/belltoy/rebar3_eetcd_plugin.git"}}
Please use '0.3.1" version instead. 💯 
https://hex.pm/packages/rebar3_eetcd_plugin

2021-12-23 04:23 UTC, belltoy commented on rebar.config
> +    {rebar3_eetcd_plugin, {git, "https://github.com/belltoy/rebar3_eetcd_plugin.git"}}
Updated

2021-12-23 13:00 UTC, merged